### ISSUE TITLE
Reproducing results on CoinRun

### ISSUE THREAD

**Issue by agarwl** [rraileanu/auto-drac#1]
I just wanted to confirm if I need to change anything before running DRAC (Random Conv) to reproduce the results reported in Table 4 and 5 in the paper -- also, why is Rand + FM (9.16) bolded instead of IBAC-SNI (9.46) for results on CoinRun in Table 5?

**Comment by rraileanu** [comment]
You don't need to change anything, you can just run `python train.py --env_name coinrun --aug_type crop` to reproduce those results. Re Table 5, you are right, that must be a mistake, IBAC-SNI is better than Rand-FM. Thanks for catching this, it will be fixed in the updated draft.

**Comment by agarwl** [comment]
Thanks!
