### ISSUE TITLE
Why do the training curves end before 25M steps?

### ISSUE THREAD

**Issue by agarwl** [rraileanu/auto-drac#6]
This might be a plotting bug or how the results are logged but it seems the training curves (picked one from the DrAC paper) are not until 25M steps but end before that: Is this the expected behavior?

![image](https://user-images.githubusercontent.com/12142945/96370568-4f346880-112c-11eb-9dcd-167e623b9fd2.png)

**Comment by rraileanu** [comment]
Yes this is due to plotting i.e. the particular way the curves are smoothed but all models were ran for 25m steps and the numbers in the tables are also computed after 25m steps. I will remove this artifact from the figures in the next version of the paper.

**Comment by agarwl** [comment]
Thanks!
